# Generated by Django 4.1.7 on 2023-03-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaaluno',
            name='dia_semana',
            field=models.IntegerField(choices=[(1, 'Domingo'), (2, 'Segunda-feira'), (3, 'Terça-feira'), (4, 'Quarta-feira'), (5, 'Quinta-feira'), (6, 'Sexta-Feira'), (7, 'Sábado')], default=2, max_length=1),
        ),
        migrations.AddField(
            model_name='materiaaluno',
            name='horario_final',
            field=models.IntegerField(choices=[(1, '07:00'), (2, '07:30'), (3, '08:00'), (4, '08:30'), (5, '09:00'), (6, '09:30'), (7, '10:00'), (8, '10:30'), (9, '11:00'), (10, '11:30'), (11, '12:00'), (12, '12:30'), (13, '13:00'), (14, '13:30'), (15, '14:00'), (16, '14:30'), (17, '15:00')], default=2, max_length=5, verbose_name='Horário Final'),
        ),
        migrations.AddField(
            model_name='materiaaluno',
            name='horario_inicial',
            field=models.IntegerField(choices=[(1, '07:00'), (2, '07:30'), (3, '08:00'), (4, '08:30'), (5, '09:00'), (6, '09:30'), (7, '10:00'), (8, '10:30'), (9, '11:00'), (10, '11:30'), (11, '12:00'), (12, '12:30'), (13, '13:00'), (14, '13:30'), (15, '14:00'), (16, '14:30'), (17, '15:00')], default=1, max_length=5, verbose_name='Horário Inicial'),
        ),
    ]
