# Generated by Django 4.1.7 on 2023-03-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_materiaaluno_dia_semana_materiaaluno_horario_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiaaluno',
            name='horario_final',
            field=models.IntegerField(choices=[('07:00', '07:00'), ('07:30', '07:30'), ('08:00', '08:00'), ('08:30', '08:30'), ('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00')], default=2, max_length=5, verbose_name='Horário Final'),
        ),
        migrations.AlterField(
            model_name='materiaaluno',
            name='horario_inicial',
            field=models.IntegerField(choices=[('07:00', '07:00'), ('07:30', '07:30'), ('08:00', '08:00'), ('08:30', '08:30'), ('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00')], default=1, max_length=5, verbose_name='Horário Inicial'),
        ),
    ]
